# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OMGSoundboard
email: marvin@omgsoundboard.audio
description: > # this means to ignore newlines until "baseurl:"
OMGSoundboard is a Badass Android Soundboard based on Material Design and the finest tunes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://omgsoundboard.github.io/" # the base hostname & protocol for your site
twitter_username: OMGSoundboard
github_username:  OMGSoundboard

# Build settings
markdown: kramdown
