- title: Fun
  description: Very fun to have. This makes meetings a lot more entertaining :)). 
  image: assets/images/service-icon5.png
- title: Ad-Free
  description: This app is amazing! No ads, easy to use, and funny. You could do so much with this. I recommend highly!
  image: assets/images/service-icon2.png
- title: Tabletop RPG
  description: This app has just the right features for using in a tabletop rpg, such as the ability to play multiple sounds concurrently and set individual looping, start time, and fading parameters
  image: assets/images/service-icon.png
- title: Podcast Creator
  description: As a Podcast Content Creator, I recommend this app, its great how you can put all or your custom sounds in it and how you can pimp out your layout, a very good app for content creators.
  image: assets/images/service-icon4.png
- title: Minecraft
  description: Very good app for making a soundboard! Now I can disturb my friends while playing Minecraft XD. IDK what to add cause it is already very good! 
  image: assets/images/service-icon6.png
- title: Ass
  description: I laugh my ass off.
  image: assets/images/service-icon3.png
