- title: Responsive Design
  description: Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.
  image: assets/images/service-icon5.png
- title: Bootstrap 4.x
  description: Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.
  image: assets/images/service-icon2.png
- title: Browser Support
  description: Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.
  image: assets/images/service-icon.png
- title: 500+ Icon Fonts
  description: Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.
  image: assets/images/service-icon4.png
- title: Creative Design
  description: Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.
  image: assets/images/service-icon6.png
- title: More Features
  description: Lorem ipsum dolor sit amet, ed do eiusmod tempor incididunt ut labore et dolore magna.
  image: assets/images/service-icon3.png